### ISSUE TITLE
Error installing "environment.yml"

### ISSUE THREAD

**Issue by RamirezArnulfo** [yinjiuxun/WaveDecompNet-paper#12]
Hello,

I'm trying to install the "environment.yml" file and I'm getting the following error in the terminal. I'm attaching a picture of the error. Do you have any idea how to fix this error?

Thank you,
Ramirez.
<img width="574" alt="image" src="https://user-images.githubusercontent.com/112971142/228946946-179adde1-3c56-4e89-b878-8e4d66780066.png">

**Comment by yinjiuxun** [comment]
Hi, I just updated and cleaned up the environment.yml file, please try again with the new yml file.
